# -*- coding: utf-8 -*-
"""youtube_single_playlist_downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtDtFlQvX7XtxmQCtGBVAt5D4297RDem
"""

# Commented out IPython magic to ensure Python compatibility.
#path where you want to donwload files
# %cd drive/MyDrive/neet/
# %ls

# Commented out IPython magic to ensure Python compatibility.
# %pip install pytube

from pytube import Playlist

#paste the link of the playlist
playlist = Playlist('https://www.youtube.com/watch?v=xxGJbc_HCEQ&list=PLw4_E5WmrJxsOOmOmLOStO-G1quj6cA1d')
print('Number of videos in playlist: %s' % len(playlist.video_urls))

def convert(s):
  ans=""
  for i in range(len(s)):
    if s[i].isalnum():
      ans+=s[i]
    else:
        if s[i]==' ':
          ans+='_'
  return ans

from pytube import YouTube
data = []
i=0
while i<(len(playlist)):
  check = False
  try :
    yt = YouTube(playlist[i])
    print(yt.title)
    yt.title = convert(yt.title)
    data.append(yt.title)
    check = True
    stream = yt.streams.first()
    #path of the folder where the donwloaded files will be present in zip format
    stream.download('/Users/rajabaidyo/Documents')
  except : 
    i-=1
    if len(data)!=0 and check==True:
      data.pop()
    print("An exception occured")
    print("Trying to download again")
  i+=1

# Create a ZipFile Object
from zipfile import ZipFile

file = open('ans'+'.zip', 'w').close()

with ZipFile('ans'+'.zip', 'w') as zipObj2:
  for i in range(len(data)):
    print(data[i])
    zipObj2.write(data[i]+'.mp4')
zipObj2.close()

#deleting of the file after the zip object formation
import os
for i in range(len(data)):
  os.system("rm "+data[i]+'.mp4')